
package kz.bsbnb.usci.wsclient.jaxb.kgd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EiccToKgdUniversalPortType", targetNamespace = "http://nationalbank.kz/ws/EiccToKgdUniversal/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EiccToKgdUniversalPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns ResponseMessage
     * @throws SendMessageException
     */
    @WebMethod(operationName = "SendMessage", action = "http://10.8.255.50:1274/EiccToKgdUniversal/SendMessage")
    @WebResult(name = "sendMessageResponse", targetNamespace = "http://nationalbank.kz/ws/EiccToKgdUniversal/", partName = "parameters")
    public ResponseMessage sendMessage(
        @WebParam(name = "sendMessageRequest", targetNamespace = "http://nationalbank.kz/ws/EiccToKgdUniversal/", partName = "parameters")
        RequestMessage parameters)
        throws SendMessageException
    ;

}
