
package kz.bsbnb.usci.wsclient.jaxb.kgd;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "sendMessageException", targetNamespace = "http://nationalbank.kz/ws/EiccToKgdUniversal/")
public class SendMessageException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionMessage faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SendMessageException(String message, ExceptionMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SendMessageException(String message, ExceptionMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ExceptionMessage
     */
    public ExceptionMessage getFaultInfo() {
        return faultInfo;
    }

}
