package kz.bsbnb.usci.receiver.pki_validator_new;

public enum PkiValidationMessage {
    SIGNATURE_NOT_FOUND,
    MORE_THAN_ONE_SIGNATURE,
    CERTIFICATE_NOT_FOUND,
    INVALID_SIGNATURE,
    CERTIFICATE_EXPIRED,
    CERTIFICATE_NOT_YET_VALID,
    OCSP_REQUEST_MISMATCH,
    OCSP_REQUEST_STATUS_REVOKED,
    OCSP_REQUEST_STATUS_UNKNOWN,
    OCSP_REQUEST_FAILED,
    UNEXPECTED_ERROR,
    NOT_AN_AUTH_KEY,
    NOT_A_SIGN_KEY,
    OID_CHECK_FAILED,
    OID_MISMATCH,
    ISSUER_CHECK_FAILED,
    ISSUER_MISMATCH,
    CHAIN_VALIDATION_FAILED, 
    UNRECOGNIZED_ALGORITHM
}
