package kz.bsbnb.usci.wsclient.jaxb.nsi;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2019-05-19T22:42:35.445+06:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "NSI_NBRK", 
                  wsdlLocation = "https://nbportal.nationalbank.kz/WebService/NSI_NBRK?wsdl",
                  targetNamespace = "http://service/") 
public class NSINBRK extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service/", "NSI_NBRK");
    public final static QName ServicePort = new QName("http://service/", "ServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://nbportal.nationalbank.kz/WebService/NSI_NBRK?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NSINBRK.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://nbportal.nationalbank.kz/WebService/NSI_NBRK?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NSINBRK(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NSINBRK(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NSINBRK() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NSINBRK(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NSINBRK(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NSINBRK(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public Service getServicePort() {
        return super.getPort(ServicePort, Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public Service getServicePort(WebServiceFeature... features) {
        return super.getPort(ServicePort, Service.class, features);
    }

}
