package kz.bsbnb.usci.wsclient.jaxb.nsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2019-05-19T22:42:35.417+06:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://service/", name = "Service")
@XmlSeeAlso({ObjectFactory.class})
public interface Service {

    @WebMethod(operationName = "GET_GUIDE")
    @Action(input = "http://service/Service/GET_GUIDERequest", output = "http://service/Service/GET_GUIDEResponse")
    @RequestWrapper(localName = "GET_GUIDE", targetNamespace = "http://service/", className = "GETGUIDE")
    @ResponseWrapper(localName = "GET_GUIDEResponse", targetNamespace = "http://service/", className = "GETGUIDEResponse")
    @WebResult(name = "return", targetNamespace = "")
    public kz.bsbnb.usci.wsclient.jaxb.nsi.ServiceResponse getGUIDE(
            @WebParam(name = "guideCode", targetNamespace = "")
                    String guideCode,
            @WebParam(name = "type", targetNamespace = "")
                    String type,
            @WebParam(name = "beginDate", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar beginDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar endDate
    );
}
