//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.02 at 11:19:52 AM ALMT 
//


package kz.bsbnb.usci.wsclient.jaxb.test;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.bsbnb.usci.wsclient.jaxb.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.bsbnb.usci.wsclient.jaxb.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AncInfo }
     * 
     */
    public AncInfo createAncInfo() {
        return new AncInfo();
    }

    /**
     * Create an instance of {@link AncInfo.Data }
     * 
     */
    public AncInfo.Data createAncInfoData() {
        return new AncInfo.Data();
    }

    /**
     * Create an instance of {@link AncInfo.Data.ContractPartiesInfo }
     * 
     */
    public AncInfo.Data.ContractPartiesInfo createAncInfoDataContractPartiesInfo() {
        return new AncInfo.Data.ContractPartiesInfo();
    }

    /**
     * Create an instance of {@link AncInfo.Header }
     * 
     */
    public AncInfo.Header createAncInfoHeader() {
        return new AncInfo.Header();
    }

    /**
     * Create an instance of {@link AncInfo.Data.ContractRegistrationInfo }
     * 
     */
    public AncInfo.Data.ContractRegistrationInfo createAncInfoDataContractRegistrationInfo() {
        return new AncInfo.Data.ContractRegistrationInfo();
    }

    /**
     * Create an instance of {@link AncInfo.Data.ContractDetailsInfo }
     * 
     */
    public AncInfo.Data.ContractDetailsInfo createAncInfoDataContractDetailsInfo() {
        return new AncInfo.Data.ContractDetailsInfo();
    }

    /**
     * Create an instance of {@link AncInfo.Data.TerminationNoticeInfo }
     * 
     */
    public AncInfo.Data.TerminationNoticeInfo createAncInfoDataTerminationNoticeInfo() {
        return new AncInfo.Data.TerminationNoticeInfo();
    }

    /**
     * Create an instance of {@link AncInfo.Data.ContractClosureInfo }
     * 
     */
    public AncInfo.Data.ContractClosureInfo createAncInfoDataContractClosureInfo() {
        return new AncInfo.Data.ContractClosureInfo();
    }

    /**
     * Create an instance of {@link AncInfo.Data.ContractPartiesInfo.ResidentInfo }
     * 
     */
    public AncInfo.Data.ContractPartiesInfo.ResidentInfo createAncInfoDataContractPartiesInfoResidentInfo() {
        return new AncInfo.Data.ContractPartiesInfo.ResidentInfo();
    }

    /**
     * Create an instance of {@link AncInfo.Data.ContractPartiesInfo.NonResidentInfo }
     * 
     */
    public AncInfo.Data.ContractPartiesInfo.NonResidentInfo createAncInfoDataContractPartiesInfoNonResidentInfo() {
        return new AncInfo.Data.ContractPartiesInfo.NonResidentInfo();
    }

}
